get http://localhost:8000/

###
get http://localhost:8000/hello

###
get http://localhost:8000/qs?p1=aa&p2=bb

###
post http://localhost:8000/hello

###
post http://localhost:8000/post-req
# json 형식으로 요청 
Content-Type: application/json; charset=UTF-8
# body에 담기 위해선 한줄 띄움 

{
    "name": "이름입니다",
    "age": 11
}

###
post http://localhost:8000/save
Content-Type: application/json; charset=UTF-8

# {
#     "name": "대한민국",
#     "capital": "서울",
#     "population": 51200000
# }
# {
#     "name": "프랑스",
#     "capital": "파리",
#     "population": 67750000
# }
# {
#     "name": "호주",
#     "capital": "캔버라",
#     "population": 25690000
# }
{
    "name": "미국",
    "capital": "워싱턴DC",
    "population": 331900000
}

# localhost:8000/list
###
get http://localhost:8000/list

# localhost:8000/1
###
get http://localhost:8000/5

# localhost:8000/1
###
put http://localhost:8000/1
Content-Type: application/json; charset=UTF-8

{
    "id": 1,
    "name": "대한민국",
    "capital": "서울",
    "population": 52000000
}

###
delete http://localhost:8000/4
